### ISSUE TITLE
 I can not understand the last step

### ISSUE THREAD

**Issue by callmeYe** [NLeSC/Cesium-NcWMS#3]
grunt serve? 
D:\apache-tomcat-8.5.15\webapps\ROOT\Cesium-NcWMS>grunt serve
Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module 'load-grunt-tasks'
Warning: Task "serve" not found. Use --force to continue.

Aborted due to warnings.

**Comment by Maartenvm** [comment]
Hi,

there's some options. I probably forgot to add a package to the package.json. 
Try `npm install --save-dev load-grunt-tasks`

Best,
Maarten
